### ISSUE TITLE
Failed to run main.py

### ISSUE THREAD

**Issue by maidmeow4** [NeverBehave/AlwaysOnline-#3]
```
INFO:root:Trying to Login to Telegram... 正在尝试登录...
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from login import client
  File "/root/devel/AlwaysOnline-/login.py", line 14, in <module>
    client = TelegramClient('session_file', api_id, api_hash, spawn_read_thread=False)
TypeError: __init__() got an unexpected keyword argument 'spawn_read_thread'
```
__another question, is it a **bad** idea to run this script as user root?__

**Comment by NeverBehave** [comment]
1) Remove that parameters 
2) no

**Comment by SpeWhite** [comment]
@NeverBehave 仍不工作
offline.py:12: RuntimeWarning: coroutine '__call__' was never awaited
  client(UpdateStatusRequest(offline=False))
加上await还是挂
